# Generated by Django 4.2.30 on 2026-05-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_prodotti_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prodotti',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prodotti',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prodotti',
            name='tipo_materiale',
            field=models.CharField(db_index=True, default=None, max_length=255),
        ),
    ]
